// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: sales.proto

package model

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idproduct string `protobuf:"bytes,1,opt,name=idproduct,proto3" json:"idproduct,omitempty"`
}

func (x *OrderProduct) Reset() {
	*x = OrderProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sales_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProduct) ProtoMessage() {}

func (x *OrderProduct) ProtoReflect() protoreflect.Message {
	mi := &file_sales_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProduct.ProtoReflect.Descriptor instead.
func (*OrderProduct) Descriptor() ([]byte, []int) {
	return file_sales_proto_rawDescGZIP(), []int{0}
}

func (x *OrderProduct) GetIdproduct() string {
	if x != nil {
		return x.Idproduct
	}
	return ""
}

type AfterOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idorder        string `protobuf:"bytes,1,opt,name=Idorder,proto3" json:"Idorder,omitempty"`
	Idproduct      string `protobuf:"bytes,2,opt,name=Idproduct,proto3" json:"Idproduct,omitempty"`
	Nameproduct    string `protobuf:"bytes,3,opt,name=Nameproduct,proto3" json:"Nameproduct,omitempty"`
	Bill           string `protobuf:"bytes,4,opt,name=Bill,proto3" json:"Bill,omitempty"`
	Status_Payment string `protobuf:"bytes,5,opt,name=Status_Payment,json=StatusPayment,proto3" json:"Status_Payment,omitempty"`
}

func (x *AfterOrder) Reset() {
	*x = AfterOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sales_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AfterOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterOrder) ProtoMessage() {}

func (x *AfterOrder) ProtoReflect() protoreflect.Message {
	mi := &file_sales_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterOrder.ProtoReflect.Descriptor instead.
func (*AfterOrder) Descriptor() ([]byte, []int) {
	return file_sales_proto_rawDescGZIP(), []int{1}
}

func (x *AfterOrder) GetIdorder() string {
	if x != nil {
		return x.Idorder
	}
	return ""
}

func (x *AfterOrder) GetIdproduct() string {
	if x != nil {
		return x.Idproduct
	}
	return ""
}

func (x *AfterOrder) GetNameproduct() string {
	if x != nil {
		return x.Nameproduct
	}
	return ""
}

func (x *AfterOrder) GetBill() string {
	if x != nil {
		return x.Bill
	}
	return ""
}

func (x *AfterOrder) GetStatus_Payment() string {
	if x != nil {
		return x.Status_Payment
	}
	return ""
}

var File_sales_proto protoreflect.FileDescriptor

var file_sales_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2c, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22,
	0xa1, 0x01, 0x0a, 0x0a, 0x41, 0x66, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x64, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x49, 0x64, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x64, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x64, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x61, 0x6d, 0x65, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x61, 0x6d,
	0x65, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x25, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x32, 0x44, 0x0a, 0x0c, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x1a, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x66, 0x74,
	0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sales_proto_rawDescOnce sync.Once
	file_sales_proto_rawDescData = file_sales_proto_rawDesc
)

func file_sales_proto_rawDescGZIP() []byte {
	file_sales_proto_rawDescOnce.Do(func() {
		file_sales_proto_rawDescData = protoimpl.X.CompressGZIP(file_sales_proto_rawDescData)
	})
	return file_sales_proto_rawDescData
}

var file_sales_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sales_proto_goTypes = []interface{}{
	(*OrderProduct)(nil), // 0: model.OrderProduct
	(*AfterOrder)(nil),   // 1: model.AfterOrder
}
var file_sales_proto_depIdxs = []int32{
	0, // 0: model.SalesService.NewOrder:input_type -> model.OrderProduct
	1, // 1: model.SalesService.NewOrder:output_type -> model.AfterOrder
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sales_proto_init() }
func file_sales_proto_init() {
	if File_sales_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sales_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sales_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AfterOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sales_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sales_proto_goTypes,
		DependencyIndexes: file_sales_proto_depIdxs,
		MessageInfos:      file_sales_proto_msgTypes,
	}.Build()
	File_sales_proto = out.File
	file_sales_proto_rawDesc = nil
	file_sales_proto_goTypes = nil
	file_sales_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SalesServiceClient is the client API for SalesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SalesServiceClient interface {
	NewOrder(ctx context.Context, in *OrderProduct, opts ...grpc.CallOption) (*AfterOrder, error)
}

type salesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSalesServiceClient(cc grpc.ClientConnInterface) SalesServiceClient {
	return &salesServiceClient{cc}
}

func (c *salesServiceClient) NewOrder(ctx context.Context, in *OrderProduct, opts ...grpc.CallOption) (*AfterOrder, error) {
	out := new(AfterOrder)
	err := c.cc.Invoke(ctx, "/model.SalesService/NewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalesServiceServer is the server API for SalesService service.
type SalesServiceServer interface {
	NewOrder(context.Context, *OrderProduct) (*AfterOrder, error)
}

// UnimplementedSalesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSalesServiceServer struct {
}

func (*UnimplementedSalesServiceServer) NewOrder(context.Context, *OrderProduct) (*AfterOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOrder not implemented")
}

func RegisterSalesServiceServer(s *grpc.Server, srv SalesServiceServer) {
	s.RegisterService(&_SalesService_serviceDesc, srv)
}

func _SalesService_NewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesServiceServer).NewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.SalesService/NewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesServiceServer).NewOrder(ctx, req.(*OrderProduct))
	}
	return interceptor(ctx, in, info, handler)
}

var _SalesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.SalesService",
	HandlerType: (*SalesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewOrder",
			Handler:    _SalesService_NewOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sales.proto",
}
