// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: park.proto

package model

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Time string `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *UserIn) Reset() {
	*x = UserIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_park_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIn) ProtoMessage() {}

func (x *UserIn) ProtoReflect() protoreflect.Message {
	mi := &file_park_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIn.ProtoReflect.Descriptor instead.
func (*UserIn) Descriptor() ([]byte, []int) {
	return file_park_proto_rawDescGZIP(), []int{0}
}

func (x *UserIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserIn) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type InputData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Platno string `protobuf:"bytes,2,opt,name=Platno,proto3" json:"Platno,omitempty"`
	Tipe   string `protobuf:"bytes,3,opt,name=Tipe,proto3" json:"Tipe,omitempty"`
}

func (x *InputData) Reset() {
	*x = InputData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_park_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_park_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputData.ProtoReflect.Descriptor instead.
func (*InputData) Descriptor() ([]byte, []int) {
	return file_park_proto_rawDescGZIP(), []int{1}
}

func (x *InputData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InputData) GetPlatno() string {
	if x != nil {
		return x.Platno
	}
	return ""
}

func (x *InputData) GetTipe() string {
	if x != nil {
		return x.Tipe
	}
	return ""
}

type UserOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Platno   string `protobuf:"bytes,2,opt,name=Platno,proto3" json:"Platno,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Duration string `protobuf:"bytes,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
}

func (x *UserOut) Reset() {
	*x = UserOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_park_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOut) ProtoMessage() {}

func (x *UserOut) ProtoReflect() protoreflect.Message {
	mi := &file_park_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOut.ProtoReflect.Descriptor instead.
func (*UserOut) Descriptor() ([]byte, []int) {
	return file_park_proto_rawDescGZIP(), []int{2}
}

func (x *UserOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserOut) GetPlatno() string {
	if x != nil {
		return x.Platno
	}
	return ""
}

func (x *UserOut) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserOut) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

var File_park_proto protoreflect.FileDescriptor

var file_park_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2c, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x47,
	0x0a, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x6c, 0x61, 0x74, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61,
	0x74, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x69, 0x70, 0x65, 0x22, 0x67, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x32, 0x72, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x6b, 0x49, 0x6e, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x6b, 0x4f, 0x75, 0x74,
	0x12, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x75, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_park_proto_rawDescOnce sync.Once
	file_park_proto_rawDescData = file_park_proto_rawDesc
)

func file_park_proto_rawDescGZIP() []byte {
	file_park_proto_rawDescOnce.Do(func() {
		file_park_proto_rawDescData = protoimpl.X.CompressGZIP(file_park_proto_rawDescData)
	})
	return file_park_proto_rawDescData
}

var file_park_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_park_proto_goTypes = []interface{}{
	(*UserIn)(nil),      // 0: model.UserIn
	(*InputData)(nil),   // 1: model.InputData
	(*UserOut)(nil),     // 2: model.UserOut
	(*empty.Empty)(nil), // 3: google.protobuf.Empty
}
var file_park_proto_depIdxs = []int32{
	3, // 0: model.ParkingService.ParkIn:input_type -> google.protobuf.Empty
	1, // 1: model.ParkingService.ParkOut:input_type -> model.InputData
	0, // 2: model.ParkingService.ParkIn:output_type -> model.UserIn
	2, // 3: model.ParkingService.ParkOut:output_type -> model.UserOut
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_park_proto_init() }
func file_park_proto_init() {
	if File_park_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_park_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_park_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_park_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_park_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_park_proto_goTypes,
		DependencyIndexes: file_park_proto_depIdxs,
		MessageInfos:      file_park_proto_msgTypes,
	}.Build()
	File_park_proto = out.File
	file_park_proto_rawDesc = nil
	file_park_proto_goTypes = nil
	file_park_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParkingServiceClient is the client API for ParkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParkingServiceClient interface {
	ParkIn(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserIn, error)
	ParkOut(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*UserOut, error)
}

type parkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingServiceClient(cc grpc.ClientConnInterface) ParkingServiceClient {
	return &parkingServiceClient{cc}
}

func (c *parkingServiceClient) ParkIn(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserIn, error) {
	out := new(UserIn)
	err := c.cc.Invoke(ctx, "/model.ParkingService/ParkIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ParkOut(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*UserOut, error) {
	out := new(UserOut)
	err := c.cc.Invoke(ctx, "/model.ParkingService/ParkOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServiceServer is the server API for ParkingService service.
type ParkingServiceServer interface {
	ParkIn(context.Context, *empty.Empty) (*UserIn, error)
	ParkOut(context.Context, *InputData) (*UserOut, error)
}

// UnimplementedParkingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedParkingServiceServer struct {
}

func (*UnimplementedParkingServiceServer) ParkIn(context.Context, *empty.Empty) (*UserIn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParkIn not implemented")
}
func (*UnimplementedParkingServiceServer) ParkOut(context.Context, *InputData) (*UserOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParkOut not implemented")
}

func RegisterParkingServiceServer(s *grpc.Server, srv ParkingServiceServer) {
	s.RegisterService(&_ParkingService_serviceDesc, srv)
}

func _ParkingService_ParkIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ParkIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.ParkingService/ParkIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ParkIn(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ParkOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ParkOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.ParkingService/ParkOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ParkOut(ctx, req.(*InputData))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParkingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.ParkingService",
	HandlerType: (*ParkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParkIn",
			Handler:    _ParkingService_ParkIn_Handler,
		},
		{
			MethodName: "ParkOut",
			Handler:    _ParkingService_ParkOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "park.proto",
}
